### ISSUE TITLE
Provide doubleshot init to create standard layout

### ISSUE THREAD

**Issue by sam** [sam/doubleshot#14]
If a Gemspec is present, then that should be read in to use during generation of your project's Doubleshot file as well.

**Comment by ckrailo** [comment]
I'll start on this.

**Comment by sam** [comment]
Created the layout for cli-commands in 12f1255ef4a604522c44ebaa5c771341547378f5.

**Comment by sam** [comment]
Closed in 6da6736f3b0bfe7698938c3f50a18f2b67f80476.
