### ISSUE TITLE
Implement JAR command

### ISSUE THREAD

**Issue by sam** [sam/doubleshot#33]
Discussion: Should we allow you to set a main-class? Or should we default to JRuby's jar-bootstrap.rb main-class?

What if you have a Java entry-point, and you really don't want to write a jar-bootstrap.rb just to call it? (Because that would almost certainly be slower.)

**Comment by sam** [comment]
Is this done then? Manifest added, `config.source.ruby` files copied in?

**Comment by ckrailo** [comment]
It still needs the ruby files.

**Comment by sam** [comment]
Assuming the `HelloRubyWorld` example I just merged works, then this is all wrapped up right?
