### ISSUE TITLE
run tests before build

### ISSUE THREAD

**Issue by ckrailo** [sam/doubleshot#34]
I remember discussing that we wanted to have tests run before the build command executes, unless `--no-test` is passed in.

Right now, tests don't run at all. One of us (probably me?) should make that happen at some point.

**Comment by sam** [comment]
Sho nuff. Go fer it. 

-Sam

**Comment by ckrailo** [comment]
Adding this to the jar command will have to wait until you accept the other pull request.

**Comment by sam** [comment]
Done.
