### ISSUE TITLE
Add a tmp/test.pid file so two test processes can't run simultaneously

### ISSUE THREAD

**Issue by sam** [sam/doubleshot#45]
Right now you can run `bin/doubleshot test` twice if you forgot about another open shell already running it. We should warn & exit.

**Comment by sam** [comment]
Right. Maybe `Pathname("/tmp")` then? Or a dotfile at-least? `Pathname(".doubleshot_test.pid")` (which is the same as what you've got, just a dotfile).

I dunno, just not in love with the idea of it dropping a pidfile in plain sight for git to pickup ya know?

**Comment by ckrailo** [comment]
Done.

**Comment by sam** [comment]
Thanks. Merged.
